import "./assets/css_reset.css";
import "./assets/styles.css";
import { Link } from 'react-router-dom';
import trivia from "./assets/trivia_wallpaper_crop.jpg"

function WelcomeBox() {
    return (
        <div>
            <br /><br />
            <div className="WelcomeBox">
                <h1 className="smallHeaderBlue"><br />Welcome to Quiz Maker / Quiz Taker<br />&nbsp;</h1>
                <img className="heroImage" src={trivia} alt="Trivia Wallpaper"></img>
                <h6><a href="https://www.vecteezy.com/free-vector/sign">Free Use Image by Vecteezy</a></h6>
                <h2 className="space">Registered Users can create their own quizzes and save scores</h2>
                <h2 className="space">Guests can take random quizzes generated by <a href="https://opentdb.com/">Open Trivia Database</a></h2>
                    <h1 class="smallHeaderBlue">
                        <Link className="link" to="/register">
                            <br />Start &#10142;
                <br />&nbsp;
                </Link>
                    </h1>
                </div>
            </div>
                    );
}

export default WelcomeBox;